### ISSUE TITLE
unexpected tag _GOVTYPE

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#16]
There was an illegal GEDCOM structure in a shared place record (manually entered by me):
`1 _LOC X164`
`2 _GOVTYPE POLI`

it should be
`1 _LOC @X164@`
`2 TYPE POLI`

When I tried to edit this element the following error was raised (maybe this error can be catched):

`unexpected tag: _GOVTYPE …/modules_v4/vesta_shared_places/patchedWebtrees/Functions/FunctionsEditLoc.php:195
#0 …/modules_v4/vesta_shared_places/patchedWebtrees/Functions/FunctionsEditLoc.php(84): Cissee\WebtreesExt\Functions\FunctionsEditLoc::addSimpleTagWithGedcomRecord(Object(Cissee\WebtreesExt\SharedPlace), Object(Cissee\WebtreesExt\CustomTree), '2 _GOVTYPE POLI', '_LOC', '<span class="er...')
#1 …/modules_v4/vesta_shared_places/resources/views/edit/edit-fact.phtml(36): Cissee\WebtreesExt\Functions\FunctionsEditLoc::createEditFormLoc(Object(Fisharebest\Webtrees\Fact))
#2 …/app/View.php(186): include('/mnt/web312/a3/...')
#3 …/app/View.php(282): Fisharebest\Webtrees\View->render()
#4 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make('edit/edit-fact', Array)
#5 …/app/Http/ViewResponseTrait.php(51): view('edit/edit-fact', Array)
#6 …/app/Http/RequestHandlers/EditFactPage.php(82): Fisharebest\Webtrees\Http\RequestHandlers\EditFactPage->viewResponse('edit/edit-fact', Array)
#7 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\EditFactPage->handle(Object(Nyholm\Psr7\ServerRequest))`

**Comment by ric2016** [comment]
Yes - unexpected tags should not cause errors.

By the way, nested shared places like this will be supported in the next release, which should be available shortly.
