### ISSUE TITLE
Error after update to webtrees 2.0.22

### ISSUE THREAD

**Issue by webtrees-pesz** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#66]
Hello Richard,

after update to 2.0.22 (from 2.0.19) following error appears:

2022-03-23 14:53:34 | error | <b>Non-static method Cissee\Webtrees\Module\Gov4Webtrees\FunctionsGov::fromRow() should not be called statically …/modules_v4/vesta_gov4webtrees/FunctionsGov.php:1993</b> <b>#0 …/modules_v4/vesta_gov4webtrees/FunctionsGov.php(1993): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8192, &#039;Non-static meth...&#039;, &#039;/var/www/web751...&#039;, 1993, Array)</b> <b>#1 …/modules_v4/vesta_gov4webtrees/FunctionsGov.php(1931): Cissee\Webtrees\Module\Gov4Webtrees\FunctionsGov::findGovParentOfTypeViaIds(Object(Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule), &#039;object_257548&#039;, Array, 2435506, Array, &#039;1640766969784&#039;)</b> <b>#2 …/modules_v4/vesta_gov4webtrees/Gov4WebtreesModule.php(646): Cissee\Webtrees\Module\Gov4Webtrees\FunctionsGov::findGovParentOfType(Object(Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule), &#039;object_257548&#039;, Object(Cissee\Webtrees\Module\Gov4Webtrees\GovObject), 2435506, Array, &#039;1640766969784&#039;)</b> <b>#3 …/modules_v4/vesta_gov4webtrees/Gov4WebtreesModule.php(577): Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule-&gt;govPgovInternal(Object(Vesta\Model\GovReference), Object(Vesta\Model\GedcomDateInterval), Object(Illuminate\Support\Collection), 9223372036854775806)</b> <b>#4 …/modules_v4/vesta_common/HookInterfaces/FunctionsPlaceUtils.php(460): Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule-&gt;govPgov(Object(Vesta\Model\GovReference), Object(Vesta\Model\GedcomDateInterval), Object(Illuminate\Support\Collection), 9223372036854775807)</b> <b>#5 …/modules_v4/vesta_common/HookInterfaces/FunctionsPlaceUtils.php(416): Vesta\Hook\HookInterfaces\FunctionsPlaceUtils::govPgov(Object(Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule), Object(Fisharebest\Webtrees\Tree), Object(Vesta\Model\GovReference), Object(Vesta\Model\GedcomDateInterval), Object(Illuminate\Support\Collection), 9223372036854775807)</b> <b>#6 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsService.php(132): Vesta\Hook\HookInterfaces\FunctionsPlaceUtils::placPplac(Object(Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule), Object(Vesta\Model\PlaceStructure), Object(Illuminate\Support\Collection))</b> <b>#7 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsService.php(229): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsService-&gt;resolvePlace(Object(Vesta\Model\PlaceStructure), Array)</b> <b>#8 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(167): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsService-&gt;getAdditionalFacts(Object(Cissee\WebtreesExt\IndividualExt), true)</b> <b>#9 …/modules_v4/vesta_personal_facts/IndividualFactsTabModuleExtended.php(208): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule-&gt;hFactsTabGetAdditionalFacts(Object(Cissee\WebtreesExt\IndividualExt))</b> #10 [internal function]: Cissee\Webtrees\Module\PersonalFacts\IndividualFactsTabModuleExtended-&gt;Cissee\Webtrees\Module\PersonalFacts\{closure}(Object(Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule), &#039;_vesta_research...&#039;) #11 …/vendor/illuminate/support/Collection.php(1120): array_map(Object(Closure), Array, Array) <b>#12 …/modules_v4/vesta_personal_facts/IndividualFactsTabModuleExtended.php(209): Illuminate\Support\Collection-&gt;map(Object(Closure))</b> <b>#13 …/modules_v4/vesta_personal_facts/patchedWebtrees/Module/IndividualFactsTabModule_2x.php(163): Cissee\Webtrees\Module\PersonalFacts\IndividualFactsTabModuleExtended-&gt;additionalFacts(Object(Cissee\WebtreesExt\IndividualExt))</b> #14 …/app/Module/ModuleTabTrait.php(116): Cissee\WebtreesExt\Module\IndividualFactsTabModule_2x-&gt;getTabContent(Object(Cissee\WebtreesExt\IndividualExt)) #15 …/app/Http/RequestHandlers/ModuleAction.php(88): Cissee\WebtreesExt\Module\IndividualFactsTabModule_2x-&gt;getTabAction(Object(Nyholm\Psr7\ServerRequest)) #16 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) <b>#18 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(226): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))</b> #19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #20 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #22 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #24 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #25 …/app/Http/Middleware/Router.php(166): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest)) #26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #27 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #29 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #31 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #32 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection)) #33 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection-&gt;transaction(Object(Closure), 3) #34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #35 …/app/Http/Middleware/DoHousekeeping.php(74): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #37 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #39 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #41 …/app/Http/Middleware/UseLanguage.php(70): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #43 …/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #45 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #47 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #49 …/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #51 …/app/Http/Middleware/BadBotBlocker.php(223): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #53 …/app/Http/Middleware/CompressResponse.php(75): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #55 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #57 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #58 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #60 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #61 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #62 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #63 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #64 …/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #65 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #66 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #67 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #68 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #69 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #70 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #71 …/app/Webtrees.php(241): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest)) #72 …/app/Webtrees.php(228): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array) #73 …/index.php(44): Fisharebest\Webtrees\Webtrees-&gt;httpRequest() #74 {main}

**Comment by ric2016** [comment]
Definitely a bug, but: Did you see the warning when using the upgrade wizard?

> The currently installed versions of the following custom modules may not be compatible with the new webtrees version 2.0.22, and there are no upgrades available yet: ⚶ Vesta Classic Look & Feel; ⚶ Vesta Clippings Cart; ⚶ Vesta Common; ⚶ Vesta Extended Relationships; ⚶ Vesta Facts and events; ⚶ Vesta Families; ⚶ Vesta Gov4Webtrees; ⚶ Vesta Places and Pedigree map; ⚶ Vesta Research Suggestions; ⚶ Vesta Shared Places; ⚶ Vesta Webtrees Location Data Provider

**Comment by ric2016** [comment]
Fixed in latest Vesta release 2.0.22.0.0.
