### ISSUE TITLE
Error in General Search for Shared Places

### ISSUE THREAD

**Issue by webtrees-pesz** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#77]
When I start a search with a GOV ID in the General search with "Shared Places" checked, the following error message appears:

assert(): assert($module instanceof SharedPlacesModule_20) failed …/modules_v4/vesta_shared_places/resources/views/search-results-ext_20.phtml:136
#0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(2, 'assert(): asser...', '/var/www/web838...', 136, Array)
#1 …/modules_v4/vesta_shared_places/resources/views/search-results-ext_20.phtml(136): assert(false, 'assert($module ...')
#2 …/app/View.php(184): include('/var/www/web838...')
#3 …/app/View.php(281): Fisharebest\Webtrees\View->render()
#4 …/app/Helpers/functions.php(200): Fisharebest\Webtrees\View::make('search-results-...', Array)
#5 …/modules_v4/vesta_shared_places/resources/views/search-general-page-ext_20.phtml(123): view('search-results-...', Array)
#6 …/app/View.php(184): include('/var/www/web838...')
#7 …/app/View.php(281): Fisharebest\Webtrees\View->render()
#8 …/app/Helpers/functions.php(200): Fisharebest\Webtrees\View::make('search-general-...', Array)
#9 …/app/Http/ViewResponseTrait.php(51): view('search-general-...', Array)
#10 …/modules_v4/vesta_shared_places/patchedWebtrees/Http/RequestHandlers/SearchGeneralPageExt_20.php(191): Cissee\WebtreesExt\Http\RequestHandlers\SearchGeneralPageExt_20->viewResponse('search-general-...', Array)
#11 …/app/Http/Middleware/WrapHandler.php(83): Cissee\WebtreesExt\Http\RequestHandlers\SearchGeneralPageExt_20->handle(Object(Nyholm\Psr7\ServerRequest))
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#13 …/modules_v4/faces/src/Modules/FacesModule.php(93): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#15 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule_20.php(231): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule_20->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))

**Comment by webtrees-pesz** [comment]
Sorry , wrong module
