### ISSUE TITLE
Bug in my log

### ISSUE THREAD

**Issue by heiler** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#96]
I tried different themes.

```
…/modules_v4/vesta_gov4webtrees/resources/css/style.css"))) AND ((("NlGV" LIKE "NlGV …/modules_v4/vesta_common/VestaModuleTrait.php:360
#0 …/app/Http/RequestHandlers/ModuleAction.php(85): Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule->getAssetAction()
#1 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()
#2 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#3 …/app/Module/CheckForNewVersion.php(122): Middleland\Dispatcher->handle()
#4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#5 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#7 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#8 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#9 …/app/Http/Middleware/Router.php(161): Fisharebest\Webtrees\Webtrees::dispatch()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#11 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#13 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#15 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#17 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#19 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#20 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#21 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#23 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#25 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#27 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#29 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#31 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#33 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#35 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle()
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#37 …/app/Http/Middleware/BadBotBlocker.php(282): Middleland\Dispatcher->handle()
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#39 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#41 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#43 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#44 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#46 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#48 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#50 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#52 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#54 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#57 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#58 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#59 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#60 {main}
```

**Comment by ric2016** [comment]
The actual error message seems to be missing unfortunately.
From the stack trace, it may be that someone attempts to load a non-existing file. Is there any way to reproduce this?
The 'AND ((("NlGV" LIKE "NlGV' part is rather dubious.

**Comment by heiler** [comment]
The html logs look like this:

```
GET /webtrees/module/_vesta_gov4webtrees_/asset?asset=css%2Fstyle.css%22)))%20AND%20(((%22NlGV%22%20LIKE%20%22NlGV&hash=fc64ac23e8b93cb3d404abb2c615b8fc%20HTTP/1.1 HTTP/1.1

GET /webtrees/module/_vesta_gov4webtrees_/asset?asset=css%2Fstyle.css%22%29%29%29%20AND%20%28%28%28%22NlGV%22%20LIKE%20%22NlGV&hash=fc64ac23e8b93cb3d404abb2c615b8fc HTTP/1.1
```

It is probably the testing process of the Sitelock Spider.

**Comment by ric2016** [comment]
Looks like it's testing for vulnerabilities via SQL injection attack then.

I can reproduce this on my website:

<https://cissee.de/webtrees2/module/_vesta_gov4webtrees_/asset?asset=css%2Fstyle.css%22)))%20AND%20(((%22NlGV%22%20LIKE%20%22NlGV&hash=fc64ac23e8b93cb3d404abb2c615b8fc>

but not locally, may be a filesystem-dependent bug, either in webtrees itself or in Vesta. I will have to investigate further. 
In any case it isn't critical, as normal users won't encounter it.
